[package]
name = "vent"
version = "0.1.0"
authors = ["Jeremy Rodi <me@medcat.me>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
nix = "0.10"
# serde_json = "1.0"
# quick-xml = "0.12.1"
error-chain = "0.11.0"
uuid = { version = "0.6", features = ["serde", "v4", "v5"] }
